matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      language: cpp
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      script:
        - export CC=clang-5.0
        - export CXX=clang++-5.0
        - mkdir build && cd build
        - cmake ..
        - make

    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      language: cpp
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - cmake
      script:
        - export CC=gcc-7
        - export CXX=g++-7
        - mkdir build && cd build
        - cmake ..
        - make

    - os: osx
      sudo: require
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
      script:
        - mkdir build && cd build
        - cmake ..
        - make